routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ListingsController@index');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index');
Route::resource('listings', 'ListingsController');

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Listing extends Model
{
    //Add One to One relationship
    public function user()
    {
    	return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // Add One to Many relationship
    public function listings()
    {
        return $this->hasMany('App\Listing');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $userId = auth()->user()->id;
        $user = User::findOrFail($userId);

        return view('dashboard')->with('listings', $user->listings);
    }
}

app/Http/Controllers/ListingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Listing;

class ListingsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listings = Listing::orderBy('created_at', 'desc')->get();
        return view('listings')->with('listings', $listings);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('createlisting');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //walidacja i ewentualny powrót z błędami walidacji
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'address' => 'required',
            'phone' => 'required',
            'bio' => 'required',
            'website' => 'required',
        ]);

        //utowrzenie obiektu klasy Listing
        $listing = new Listing();
        $listing->name = $request->input('name');
        $listing->email = $request->input('email');
        $listing->phone = $request->input('phone');
        $listing->address = $request->input('address');
        $listing->website = $request->input('website');
        $listing->bio = $request->input('bio');
        $listing->user_id = auth()->user()->id;

        //proba zapisania danych i przekierowanie na 
        //index listingow lub create w zaleznosci od sukcesu
        try {
            $listing->save();
            return redirect('/dashboard')
                    ->with('success', 'Dodano wizytówkę');
        } catch (\Exception $e) {
            return redirect('/dashboard')
                    ->with('error', 'Nie dodano wizytówki! ' . $e->getMessage());
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $listing = Listing::findOrFail($id);

        if ($listing->user_id != auth()->user()->id) {
            return redirect('/')->with('error', 'Brak dostępu');
        }

        return view('edit')->with('listing', $listing);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //walidacja i ewentualny powrót z błędami walidacji
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'address' => 'required',
            'phone' => 'required',
            'bio' => 'required',
            'website' => 'required',
        ]);

        //pobranie obiektu klasy Listing
        $listing = Listing::findOrFail($id);
        if ($listing->user_id != auth()->user()->id) {
            return redirect('/')->with('error', 'Brak dostępu');
        }
        $listing->name = $request->input('name');
        $listing->email = $request->input('email');
        $listing->phone = $request->input('phone');
        $listing->address = $request->input('address');
        $listing->website = $request->input('website');
        $listing->bio = $request->input('bio');
        $listing->user_id = auth()->user()->id;

        //proba zapisania danych i przekierowanie na 
        //index listingow lub create w zaleznosci od sukcesu
        try {
            $listing->save();
            return redirect('/dashboard')
                    ->with('success', 'Zapisano wizytówkę');
        } catch (\Exception $e) {
            return redirect('/dashboard')
                    ->with('error', 'Nie zapisano wizytówki! ' . $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $listing = Listing::findOrFail($id);
        if ($listing->user_id != auth()->user()->id) {
            return redirect('/')->with('error', 'Brak dostępu');
        }
        if ($listing->delete()) {
            return redirect('/dashboard')
                    ->with('success', 'Usunięto wizytówkę');
        } else {
            return redirect('/dashboard')
                    ->with('error', 'Nie usunięto wizytówki');
        }
    }
}

resources/views/createlisting.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Create Listing</h3>
			</div>
			<div class="panel-body">
				{!! Form::open(['action' => 'ListingsController@store', 'method' => 'POST'])!!}
					{{ Form:: bsText('name', null, 'Nazwa firmy',  ['placeholder' => 'Nazwa firmy'])}}
					{{ Form:: bsText('email', null, 'Email firmy',  ['placeholder' => 'Email firmy'])}}
					{{ Form:: bsText('website', null, 'WWW firmy',  ['placeholder' => 'WWW firmy'])}}
					{{ Form:: bsText('phone', null, 'Tel firmy',  ['placeholder' => 'Tel firmy'])}}
					{{ Form:: bsText('address', null, 'Adres firmy',  ['placeholder' => 'Adres firmy'])}}
					{{ Form:: bsTextarea('bio', null, 'Opis firmy',  ['placeholder' => 'Opis firmy'])}}
					{{ Form:: bsSubmit('Dodaj', ['class' => 'btn btn-success'])}}
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Dashboard
                    <span class="pull-right">
                        <a href="{{ route('listings.create') }}" class="btn btn-success btn-xs">Add listing</a>
                    </span>
                </div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h3>Twoje firmy</h3>
                    @if (count($listings))
                       <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Nazwa firmy</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($listings as $listing)
                                    <tr>
                                        <td>{{$listing->name}}</td>
                                        <td>
                                            <a href="{{ route('listings.edit', ['id' => $listing->id]) }}" class="pull-right btn btn-primary">Edycja</a>
                                        </td>
                                        <td>
                                            {!! Form::open([
                                                'action' => ['ListingsController@destroy', 'id' => $listing->id ], 
                                                'method' => 'POST', 
                                                'class' => 'pull-right',
                                                'onsubmit' => 'return confirm("Czy na pewno usunąć")'
                                                ]) 
                                            !!}
                                                {{ Form::hidden('_method', 'DELETE')}}
                                                {{ Form::bsSubmit('Usuń', ['class' => 'btn btn-danger'])}}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table> 
                    @else
                        <div class="alert alert-warning">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Uwaga!</strong> Brak firm!
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Edycja Wizytówki</h3>
			</div>
			<div class="panel-body">
				{!! Form::open(['action' => ['ListingsController@update', 'id' => $listing->id], 'method' => 'POST'])!!}
					{{ Form::hidden('_method', 'PUT')}}
					{{ Form::bsText('name', $listing->name, 'Nazwa firmy',  ['placeholder' => 'Nazwa firmy'])}}
					{{ Form::bsText('email', $listing->email, 'Email firmy',  ['placeholder' => 'Email firmy'])}}
					{{ Form::bsText('website', $listing->website, 'WWW firmy',  ['placeholder' => 'WWW firmy'])}}
					{{ Form::bsText('phone', $listing->phone, 'Tel firmy',  ['placeholder' => 'Tel firmy'])}}
					{{ Form::bsText('address', $listing->address, 'Adres firmy',  ['placeholder' => 'Adres firmy'])}}
					{{ Form::bsTextarea('bio', $listing->bio, 'Opis firmy',  ['placeholder' => 'Opis firmy'])}}
					{{ Form::bsSubmit('Zapisz', ['class' => 'btn btn-success'])}}
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/inc/alerts.blade.php
<div class="row">
	<div class="col-xs-12" id="alert-messages">
		<!-- wyswietlanie bledow formularza -->
		@if (count($errors) > 0)
			@foreach ($errors->all() as $error)
				<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ $error }}
				</div>
			@endforeach
		@endif

		<!-- error message do pokazywania bledow zapisow do bazy danych -->
		@if (session('error'))
			<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ session('error') }}
				</div>
		@endif

		<!-- success message do pokazywania udanego zapisu do bazy danych -->
		@if (session('success'))
			<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ session('success') }}
				</div>
		@endif
	</div>
</div>

resources/views/inc/navbar.blade.php
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
      <div class="navbar-header">

          <!-- Collapsed Hamburger -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>

          <!-- Branding Image -->
          <a class="navbar-brand" href="{{ url('/') }}">
              {{ config('app.name', 'Laravel') }}
          </a>
      </div>

      <div class="collapse navbar-collapse" id="app-navbar-collapse">
          <!-- Left Side Of Navbar -->
          <ul class="nav navbar-nav">
              &nbsp;
          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="nav navbar-nav navbar-right">
              <!-- Authentication Links -->
              @guest
                  <li><a href="{{ route('login') }}">Login</a></li>
                  <li><a href="{{ route('register') }}">Register</a></li>
              @else
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                          {{ Auth::user()->name }} <span class="caret"></span>
                      </a>

                      <ul class="dropdown-menu">
                          <li>
                              <a href="{{ route('logout') }}"
                                  onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                                  Logout
                              </a>

                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                  {{ csrf_field() }}
                              </form>
                          </li>
                      </ul>
                  </li>
              @endguest
          </ul>
      </div>
  </div>
</nav>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('inc.navbar')
        <div class="container">
            @include('inc.alerts')
            @yield('content')
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/listings.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Dashboard
                    <span class="pull-right">
                        <a href="{{ route('listings.create') }}" class="btn btn-success btn-xs">Add listing</a>
                    </span>
                </div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (count($listings))
                       <ul class="list-group">
                           @foreach($listings as $listing)
                            <li class="list-group-item">
                                <a href="/listings/{{$listing->id}}/edit">{{$listing->name}}</a>
                            </li>
                           @endforeach
                       </ul>
                    @else
                        <div class="alert alert-warning">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Uwaga!</strong> Brak firm!
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection